package baseline

import (
	"testing"
)

func TestExecutionModelFinalAcceptanceMatrix(t *testing.T) {
	t.Run("compiled-island-call-chain", TestBaselineRuntimeCallStubChainsAcrossCompiledFrames)
	t.Run("nested-compiled-call-host-boundary", TestBaselineRuntimeNestedCompiledCallCanReachHostBoundary)
	t.Run("native-builtin-island-composition", TestBaselineRuntimeNativeBuiltinCompositionStaysInCompiledIsland)
	t.Run("compiled-proto-cache", TestBaselineRuntimeCachesCompiledProtoByRef)
	t.Run("shared-stub-feedback", TestBaselineRuntimeFeedbackTransitionsMatchInterpreter)
	t.Run("table-slow-stub-call-continuation", TestBaselineRuntimeTableSlowStubContinuesIntoCall)
	t.Run("metatable-blocker-hit-stays-covered", TestBaselineRuntimeMetatableBlockedTableUsesSharedSlowStub)
	t.Run("metatable-blocker-miss-slow-stub", TestBaselineRuntimeMetatableBlockedMissUsesSharedSlowStub)
	t.Run("global-metatable-slow-stub", TestBaselineRuntimeGlobalMetamethodsStayInCompiledIsland)
	t.Run("self-metatable-slow-stub", TestBaselineRuntimeSelfMetamethodUsesSharedSlowStub)
	t.Run("len-slow-stub", TestBaselineRuntimeLenStubResumesCompiledContinuation)
	t.Run("setglobal-native-builtin", TestBaselineRuntimeCompiledSetGlobalFastPathAfterWarmup)
	t.Run("real-deopt-continuation", TestBaselineRuntimeDeoptResumesWithoutReplayingEarlierSideEffects)
	t.Run("host-bridge-continuation", TestBaselineRuntimeHostBridgeStubsResumeCompiledContinuation)
	t.Run("host-descriptor-refresh", TestBaselineRuntimeHostDescriptorRefreshKeepsCompiledContinuation)
	t.Run("upvalue-get-stub-continuation", TestBaselineRuntimeUpvalueStubsResumeCompiledContinuation)
	t.Run("upvalue-set-stub-continuation", TestBaselineRuntimeSetUpvalueStubResumesCompiledContinuation)
	t.Run("closed-upvalue-native-builtin", TestBaselineRuntimeClosedUpvalueNativeBuiltinResumesCompiledContinuation)
	t.Run("upvalue-open-return-top", TestBaselineRuntimeOpenReturnUsesUpdatedTopAfterGetUpvalueBuiltin)
	t.Run("host-getglobal-open-return-top", TestBaselineRuntimeOpenReturnUsesUpdatedTopAfterHostGetGlobalStub)
	t.Run("vararg-fixed", TestBaselineRuntimeCompiledVarargFixedCountWithNilFill)
	t.Run("vararg-open", TestBaselineRuntimeCompiledVarargOpenFormSupportsOpenReturn)
	t.Run("setlist-fast-path", TestBaselineRuntimeCompiledSetListFastPath)
	t.Run("setlist-open-count", TestBaselineRuntimeCompiledSetListOpenCountFromVararg)
	t.Run("tforloop-lua-iterator", TestBaselineRuntimeCompiledTForLoopWithLuaIterator)
	t.Run("tforloop-host-boundary", TestBaselineRuntimeTForLoopHostBoundaryResumesCompiledContinuation)
	t.Run("tforloop-open-return-top", TestBaselineRuntimeTForLoopPreservesOpenReturnTop)
	t.Run("setlist-payload-fallback", TestBaselineRuntimeSetListPayloadFallbackResumesContinuation)
	t.Run("tailcall-continuation", TestBaselineRuntimeCompiledTailCall)
	t.Run("nested-compiled-tailcall-host-boundary", TestBaselineRuntimeNestedCompiledTailCallCanReachHostBoundary)
	t.Run("loop-backedge-continuation", TestBaselineRuntimeLoopSlowStubResumesContinuation)
	t.Run("table-layering-audit", TestTableLoweringStaysOnFastPathDispatchLayer)
	t.Run("runtime-stub-host-boundary-audit", TestRuntimeStubsUseSharedHostBoundary)
	t.Run("runtime-stub-batch3-native-audit", TestRuntimeStubsDoNotOwnBatch3NativeBuiltins)
	t.Run("runtime-stub-batch2-native-audit", TestRuntimeStubsDoNotOwnBatch2NativeBuiltins)
	t.Run("stub-manager-batch2-native-install-audit", TestStubManagerInstallsNativeUpvalueAndLoopBodies)
	t.Run("stub-manager-covered-native-install-audit", TestStubManagerInstallsAllCoveredNativeBuiltinBodies)
	t.Run("stub-manager-batch4-native-install-audit", TestStubManagerInstallsNativeCallAndTailBodies)
	t.Run("runtime-stub-batch4-nested-audit", TestRuntimeStubsFinishNestedCompiledCalls)
	t.Run("native-builtin-abi-layout", TestNativeBuiltinABIContractLayout)
	t.Run("native-builtin-entry-trampoline-contract", TestCompiledEntryTrampolinePreservesBuiltinABIRegisters)
	t.Run("native-builtin-continuation-metadata-contract", TestCompilerEmitsNativeBuiltinContinuationContracts)
}
